### ISSUE TITLE
401 on Login-POST

### ISSUE THREAD

**Issue by kdotzlaw** [kdotzlaw/StudyBuddy#107]
Login-POST response gives 401 error, indicating incorrect username/password. 
 File "C:\Users\andre\Documents\GitHub\StudyBuddy\backend\server.py", line 78, in request_loader
    username = request.get_json(force=True)['username']
KeyError: 'username'

**Comment by kdotzlaw** [comment]
Also causes issues when adding requirements

**Comment by rdotzlaw** [comment]
caused by missing 'username' key in JSON. this was fixed sometime between now and the creation of the issue, so marking as fixed
